import React, { Suspense, lazy, memo, useMemo, useState } from "react";

function resolveInjected(props = {}) {
  const parseMaybe = (value) => {
    if (!value) return null;
    if (typeof value === "string") { try { return JSON.parse(value); } catch { return null; } }
    if (typeof value === "object" && !Array.isArray(value)) return value;
    return null;
  };
  for (const source of [props.blueprint, props.data, props.payload, props.chatData, props.input, props.injected]) {
    const parsed = parseMaybe(source); if (parsed) return parsed;
  }
  if (typeof window !== "undefined") {
    for (const source of [window.__INJECTED__, window.__CHAT_DATA__, window.CLAUDE_BLUEPRINT, window.BLUEPRINT_JSON, window.__BLUEPRINT__]) {
      const parsed = parseMaybe(source); if (parsed) return parsed;
    }
    const script = typeof document !== "undefined" ? document.querySelector('script[type="application/json"][data-blueprint]') : null;
    if (script) { const parsed = parseMaybe(script.textContent); if (parsed) return parsed; }
  }
  return null;
}

const cx={wrap:{fontFamily:"system-ui,-apple-system,Segoe UI,sans-serif",fontSize:13,maxWidth:1100,margin:"0 auto",color:"var(--color-text-primary)"},h1:{fontSize:22,margin:"4px 0 6px"},sub:{color:"var(--color-text-secondary)",lineHeight:1.55},card:{border:".5px solid var(--color-border-tertiary)",borderRadius:10,padding:14,marginBottom:10,background:"var(--color-background-primary)"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10},badge:{display:"inline-block",border:".5px solid var(--color-border-secondary)",borderRadius:999,padding:"2px 8px",fontSize:11,color:"var(--color-text-secondary)"},tab:a=>({border:".5px solid var(--color-border-secondary)",borderRadius:8,padding:"7px 11px",background:a?"var(--color-background-secondary)":"transparent",color:"var(--color-text-primary)",cursor:"pointer"})};
function asArray(v){return Array.isArray(v)?v:[];} function val(v,d="—"){return v===0||v?String(v):d;} function Section({title,children}){return <section style={cx.card}><div style={{fontWeight:650,marginBottom:8}}>{title}</div>{children}</section>;} function Empty(){return <Section title="Brak danych">Brak blueprintu. Renderer oczekuje danych przez props.blueprint / props.data albo window.__INJECTED__.</Section>}
const Meta=memo(function Meta({bp}){return <><div style={cx.grid}><Section title="Dziedzina"><b>{val(bp.dziedzina)}</b><div style={cx.sub}>{val(bp.przepis)} · {val(bp.czyn)}</div></Section><Section title="Etap"><b>{val(bp.etap)}</b><div style={cx.sub}>Sygnatura: {val(bp.sygnatura)}</div></Section><Section title="Pilność"><b>{val(bp.pilnosc)}</b><div style={cx.sub}>Termin: {val(bp.termin)}</div></Section><Section title="Pewność raportu"><b>{val(bp.confidence||bp.pewnosc)}/10</b><div style={cx.sub}>{val(bp.confidence_note||bp.uwagi_pewnosci)}</div></Section></div><Section title="Stan faktyczny"><div style={cx.sub}>{val(bp.zdarzenie)}</div>{bp.skutki&&<div style={cx.sub}>Skutki: {bp.skutki}</div>}</Section></>});
const Sources=memo(function Sources({bp}){const items=asArray(bp.sources||bp.zrodla||bp.source_status);return <Section title="Status źródeł A/B/C/D/E">{items.length?items.map((s,i)=><div key={i} style={{padding:"7px 0",borderBottom:".5px solid var(--color-border-tertiary)"}}><b>{val(s.status||s.ocena||s.level)}</b> <span style={cx.badge}>{val(s.type||s.typ)}</span><div style={cx.sub}>{val(s.name||s.nazwa||s.opis)}</div><div style={cx.sub}>Wpływ: {val(s.impact||s.wplyw)} · Ryzyko: {val(s.risk||s.ryzyko)}</div></div>):<div style={cx.sub}>Brak tabeli źródeł w blueprint.</div>}</Section>});
const Evidence=memo(function Evidence({bp}){return <Section title="Dowody">{asArray(bp.dowody||bp.evidence).map((d,i)=><div key={i} style={{padding:"7px 0",borderBottom:".5px solid var(--color-border-tertiary)"}}><b>{val(d.opis||d.name)}</b> <span style={cx.badge}>{val(d.poziom||d.level||d.source_status)}</span><div style={cx.sub}>{val(d.typ||d.type)} · Źródło: {val(d.zrodlo||d.source)} · Ryzyko: {val(d.ryzyko||d.risk)}</div></div>)}</Section>});
const Risks=memo(function Risks({bp}){const risks=asArray(bp.risk_map||bp.ryzyka||bp.risks);return <Section title="Mapa ryzyk procesowych">{risks.length?risks.map((r,i)=><div key={i} style={{padding:"7px 0",borderBottom:".5px solid var(--color-border-tertiary)"}}><b>{val(r.level||r.poziom||r.ocena)}</b> — {val(r.name||r.ryzyko||r.text)}<div style={cx.sub}>Prawdopodobieństwo: {val(r.probability||r.prawdopodobienstwo)} · Wpływ: {val(r.impact||r.wplyw)}</div><div style={cx.sub}>Mitigacja: {val(r.mitigation||r.rekomendacja)}</div></div>):<div style={cx.sub}>Brak mapy ryzyk w blueprint.</div>}</Section>});
const Conflicts=memo(function Conflicts({bp}){const items=asArray(bp.conflicts||bp.sprzecznosci||bp.gaps);return <Section title="Sprzeczności i luki">{items.length?items.map((c,i)=><div key={i} style={{padding:"7px 0",borderBottom:".5px solid var(--color-border-tertiary)"}}><b>{val(c.type||c.typ||c.level)}</b><div style={cx.sub}>{val(c.description||c.opis||c.text)}</div><div style={cx.sub}>Działanie: {val(c.action||c.recommendation||c.rekomendacja)}</div></div>):<div style={cx.sub}>Brak wykazanych sprzeczności/luk.</div>}</Section>});
const Actions=memo(function Actions({bp}){const items=asArray(bp.procedural_recommendations||bp.recommendations||bp.rekomendacje);return <><Section title="Rekomendacje procesowe">{items.length?items.map((a,i)=><p key={i} style={cx.sub}>{i+1}. {val(a.text||a.rekomendacja||a)} {a.deadline||a.termin?<b> — {a.deadline||a.termin}</b>:null}</p>):<div style={cx.sub}>Brak rekomendacji procesowych.</div>}</Section><Section title="Następny krok"><div style={cx.sub}>{val(bp.nastepnyKrok||bp.next_step)}</div></Section></>});
const Prediction=memo(function Prediction({bp}){return <><Section title="Predykcja"><div style={{fontSize:24,fontWeight:700}}>{val(bp.p1pct||bp.prediction_pct,0)}%</div><b>{val(bp.p1lbl||bp.prediction_label)}</b><div style={cx.sub}>{val(bp.p1opis||bp.prediction_note)}</div></Section></>});
const panels={meta:lazy(()=>Promise.resolve({default:Meta})),sources:lazy(()=>Promise.resolve({default:Sources})),evidence:lazy(()=>Promise.resolve({default:Evidence})),risks:lazy(()=>Promise.resolve({default:Risks})),conflicts:lazy(()=>Promise.resolve({default:Conflicts})),actions:lazy(()=>Promise.resolve({default:Actions})),prediction:lazy(()=>Promise.resolve({default:Prediction}))};
export default function App(props = {}){const bp=useMemo(()=>resolveInjected(props)||{},[props]);const [tab,setTab]=useState("meta");const Panel=panels[tab];const tabs=[["meta","Sprawa"],["sources","Źródła"],["evidence","Dowody"],["risks","Ryzyka"],["conflicts","Sprzeczności"],["actions","Działania"],["prediction","Prognoza"]];return <div style={cx.wrap}><header style={{marginBottom:14}}><div style={cx.badge}>RAPORT_SYTUACYJNY_BLUEPRINT · tryb {val(bp.tryb)}</div><h1 style={cx.h1}>{val(bp.title,"Raport sytuacyjny sprawy")}</h1><div style={cx.sub}>{val(bp.sygnatura)} · {val(bp.data)}</div></header><div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:12}}>{tabs.map(([k,l])=><button key={k} style={cx.tab(tab===k)} onClick={()=>setTab(k)}>{l}</button>)}</div>{Object.keys(bp).length?<Suspense fallback={<Section title="Ładowanie">Ładowanie panelu…</Section>}><Panel bp={bp}/></Suspense>:<Empty/>}</div>}
