#!/usr/bin/env python3
from pathlib import Path
import shutil,re,hashlib,subprocess

BASE=Path('Wersja rozwojowa rozpakowana')
SRC=BASE/'audyt-systemu-v4'
SHARED=BASE/'shared'
OUTP=Path('staging'); OUT=OUTP/'audyt-systemu-v4'
if OUTP.exists(): shutil.rmtree(OUTP)
OUTP.mkdir(); shutil.copytree(SRC,OUT)
source=[p for p in SRC.rglob('*') if p.is_file() and '__pycache__' not in p.parts]
# Remove any generated bytecode from copied source, if present.
for d in list(OUT.rglob('__pycache__')): shutil.rmtree(d)
for f in list(OUT.rglob('*.pyc'))+list(OUT.rglob('*.pyo')): f.unlink()
assert len(source)==len([p for p in OUT.rglob('*') if p.is_file()])
assert len(source)<=198

p=OUT/'SKILL.md'; t=p.read_text(encoding='utf-8')
desc='Audyt jakości, spójności i bezpieczeństwa systemu prawnych skilli: zależności, wersje, mapy Dz.U., treść merytoryczna, propagacja zmian, deduplikacja i bramki jakości.'
# description may be plain scalar already
t=re.sub(r'^description:\s*.*$',f'description: "{desc}"',t,count=1,flags=re.M)
# replace compatibility list with host-neutral declaration
pat=re.compile(r'^compatibility:\s*\n(?:^[ \t]+- .*\n?)+',re.M)
t,n=pat.subn('compatibility: "ChatGPT, Claude, modular legal skills; file_read, live_web_lookup, optional artifact/UI tooling"\n',t,count=1)
if n!=1:
    t=re.sub(r'^compatibility:\s*.*$','compatibility: "ChatGPT, Claude, modular legal skills; file_read, live_web_lookup, optional artifact/UI tooling"',t,count=1,flags=re.M)
adapter='''## ADAPTER RUNTIME — PORTABILITY (ChatGPT / Claude / inne hosty)\n\nTa sekcja zmienia wyłącznie wykonanie operacji technicznych. Tryby audytu, zasady kontroli merytorycznej, map Dz.U., deduplikacji, propagacji zmian, rejestrów i bramek jakości pozostają bez zmian.\n\n1. `view /mnt/skills/user/audyt-systemu-v4/<plik>` oraz względne odwołania do `modules/`, `references/`, `scripts/` i `widgets/` oznaczają świeży odczyt lokalnego zasobu tego skilla. Literalna ścieżka `/mnt/skills/user` nie jest wymagana.\n2. `view /mnt/skills/user/shared/<plik>` oznacza świeży odczyt z osobnego, kanonicznego skilla `shared`. NIE kopiuj `shared` do paczki audytora. Brak obowiązkowego zasobu = fail-closed.\n3. `view /mnt/skills/user/<inny-skill>/<plik>` oznacza odczyt/aktywację osobnego skilla przez mechanizm hosta. Audyt może kontrolować zależności między skillami, ale nie vendoryzuje ich.\n4. `web_search` / `web_fetch` oznaczają świeże wyszukanie i odczyt źródła przez równoważną funkcję hosta. Przy audycie prawa zachowaj wymóg źródeł oficjalnych i nie traktuj pamięci modelu jako weryfikacji.\n5. `present_files`, `create_file`, `show_widget`, `visualize:read_me`, Cowork i podobne nazwy są operacjami semantycznymi. Użyj równoważnej natywnej funkcji hosta, jeśli istnieje; jeśli nie, zastosuj tekstowy/plikowy fallback bez fikcyjnego raportowania wykonania.\n6. Skrypty w `scripts/` mają wykrywać root repo względnie lub z `REPO_ROOT`/`LEX_MACHINA_ROOT`; nie zakładaj `/mnt/skills/user`. Twardy limit wydania pozostaje 200 plików na skill.\n7. Audyt treści i narzędzi może raportować Claude-specific lub ChatGPT-specific tokeny jako portability warnings; sama obecność legacy nazwy nie jest automatycznie błędem, jeśli adapter semantyczny zapewnia równoważne wykonanie.\n8. Nie ujawniaj prywatnego chain-of-thought jako produktu audytu. Raportuj wykryte fakty, ślady weryfikacji, testy, różnice, ryzyka i rekomendowane poprawki.\n\n**Zasada nadrzędna:** instrukcje, które są już zrozumiałe i wykonalne w bieżącym hoście, wykonuj bez konwersji. Adapter działa wyłącznie na granicy runtime.\n\n'''
if not t.startswith('---\n'): raise SystemExit('frontmatter missing')
idx=t.find('\n---\n',4)
if idx<0: raise SystemExit('frontmatter close missing')
ins=idx+5
t=t[:ins]+'\n'+adapter+t[ins:]
p.write_text(t,encoding='utf-8')

# Verify active canonical shared refs in the whole own skill tree.
TEXT={'.md','.txt','.json','.py','.sh','.yaml','.yml','.html','.jsx','.js','.mjs'}
missing=[]; refs=set()
for f in [x for x in OUT.rglob('*') if x.is_file()]:
    if f.suffix.lower() not in TEXT: continue
    try:d=f.read_text(encoding='utf-8')
    except UnicodeDecodeError: continue
    for m in re.finditer(r'\bview\s+/mnt/skills/user/shared/([A-Za-z0-9_./-]+\.(?:md|json|txt|py|sh|ya?ml|html|jsx|js|mjs))',d):
        rel=m.group(1); refs.add(rel)
        if not (SHARED/rel).is_file(): missing.append(rel)
if missing: raise SystemExit('missing canonical shared refs: '+', '.join(sorted(set(missing))))
if (OUT/'shared').exists(): raise SystemExit('vendored shared present')

# Syntax checks; clean generated bytecode afterwards.
for py in sorted((OUT/'scripts').glob('*.py')):
    subprocess.run(['python','-m','py_compile',str(py)],check=True)
subprocess.run(['bash','-n',str(OUT/'scripts/dostarcz_skill.sh')],check=True)
for d in list(OUT.rglob('__pycache__')): shutil.rmtree(d)
for f in list(OUT.rglob('*.pyc'))+list(OUT.rglob('*.pyo')): f.unlink()

manifest=[
'# Portability manifest — audyt-systemu-v4','',
'- Source baseline: `bdebb4b0b6ba63add44501795c6e4acdc5bfd931` plus prior portability fixes to audit scripts on `portability/audyt-systemu-v4-01`.',
'- Full own skill tree preserved; no `shared` or other skill is vendored.',
'- `SKILL.md` now explicitly supports both ChatGPT and Claude through a semantic runtime adapter.',
f'- Source files preserved before manifest/checksums: **{len(source)}**',
f'- Verified active canonical shared refs: **{len(refs)}**',
f'- Frontmatter description: **{len(desc)}/200** characters.','',
'## Existing portability fixes retained','',
'- Repository root detection and `REPO_ROOT` / `LEX_MACHINA_ROOT` support in scripts.',
'- One skill = one complete ZIP; hard limit 200 files.',
'- Regression suite propagates the detected root.',
'- Shared CI reports runtime-specific paths/tokens as portability findings rather than assuming one host.','']
(OUT/'PORTABILITY-MANIFEST.md').write_text('\n'.join(manifest),encoding='utf-8')
rows=[]
for f in sorted(x for x in OUT.rglob('*') if x.is_file() and x.name!='CHECKSUMS.sha256'):
    rows.append(f'{hashlib.sha256(f.read_bytes()).hexdigest()}  {f.relative_to(OUT).as_posix()}')
(OUT/'CHECKSUMS.sha256').write_text('\n'.join(rows)+'\n',encoding='utf-8')
final=len([x for x in OUT.rglob('*') if x.is_file()])
assert final<=200
assert not list(OUT.rglob('*.pyc')) and not list(OUT.rglob('__pycache__'))
print(f'SUCCESS SOURCE={len(source)} FINAL={final} SHARED_REFS={len(refs)} DESC={len(desc)}')
